apiVersion: v1
kind: Pod
metadata:
  name: php
spec:
  containers:
    - name: php
      image: php:apache
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web
          mountPath: /var/www/html
  volumes:
    - name: web
      hostPath:
        path: /run/desktop/mnt/host/d/projects/EDR Viborg
        type: Directory